<?php
return array (
  'products_per_page' => 30,
  'reviews_per_page_total' => 30,
  'reviews_per_page_product' => 5,
  'review_highlight_time' => 180,
  'products_default_view' => 'table',
  'orders_default_view' => 'split',
  'orders_per_page' => 
  array (
    'split' => 15,
    'table' => 30,
  ),
  'orders_update_list' => 60000,
  'image_sizes' => 
  array (
    0 => '200x200',
  ),
  'image_max_size' => 1000,
  'image_sharpen' => 0,
  'image_thumbs_on_demand' => 1,
  'image_save_original' => 1,
  'order_state_icons' => 
  array (
    0 => 'new',
    1 => 'processing',
    2 => 'paid',
    3 => 'sent',
    4 => 'completed',
    5 => 'refunded',
    6 => 'trash',
    7 => 'flag-white',
    8 => 'flag-blue',
    9 => 'flag-yellow',
    10 => 'flag-green',
    11 => 'flag-red',
    12 => 'flag-purple',
    13 => 'flag-black',
    14 => 'flag-checkers',
  ),
  'type_icons' => 
  array (
    0 => 'ss pt box',
    1 => 'ss pt sports',
    2 => 'ss pt soccer',
    3 => 'ss pt cake',
    4 => 'ss pt music',
    5 => 'ss pt car',
    6 => 'ss pt diamond',
    7 => 'ss pt audio',
    8 => 'ss pt globe',
    9 => 'ss pt mobile',
    10 => 'ss pt gingerbread-man',
    11 => 'ss pt camera',
    12 => 'ss pt rocket',
    13 => 'ss pt plane',
    14 => 'ss pt shoe',
    15 => 'ss pt gift',
    16 => 'ss pt nuclear',
    17 => 'ss pt map',
    18 => 'ss pt tv',
    19 => 'ss pt t-shirt',
    20 => 'ss pt disc',
    21 => 'ss pt computer',
    22 => 'ss pt building',
    23 => 'ss pt toolbox',
    24 => 'ss pt hamburger',
    25 => 'ss pt cookie',
    26 => 'ss pt door',
    27 => 'ss pt clapperboard',
    28 => 'ss pt traffic-cone',
    29 => 'ss pt hammer',
    30 => 'ss pt guitar',
    31 => 'ss pt disk',
    32 => 'ss pt cup',
    33 => 'ss pt auction-hammer',
    34 => 'ss pt drawer',
    35 => 'ss pt traffic-light',
    36 => 'ss pt clock',
    37 => 'ss pt chair',
    38 => 'ss pt downloadable',
    39 => 'ss pt sunglasses',
    40 => 'ss pt umbrella',
    41 => 'ss pt controller',
    42 => 'ss pt key',
    43 => 'ss pt sushi',
    44 => 'ss pt cat',
    45 => 'ss pt monkey',
    46 => 'ss pt socket',
    47 => 'ss pt spray',
  ),
);